### ISSUE TITLE
Lorempixel extension not working

### ISSUE THREAD

**Issue by Moini** [Xaviju/inkscape-placeholder#1]
With latest revision from Nov 7, 2015, I get this traceback when I try to use the lorempixel extension (the other two work well):

Traceback (most recent call last):
  File "lorempixel.py", line 52, in <module>
    placeholder.affect()
  File "/usr/share/inkscape/extensions/inkex.py", line 268, in affect
    self.effect()
  File "lorempixel.py", line 20, in effect
    image = self._get_image()
  File "lorempixel.py", line 31, in _get_image
    context = ssl._create_unverified_context()
AttributeError: 'module' object has no attribute '_create_unverified_context'

It seems this has to do with my Python being Python 2.7.6, and the private functions used here are only available from python 2.7.9 upwards.

Wasn't able to solve the problem, though :-/, I don't know enough about python/ssl/urllib .
(solved it for myself by turning https into http, but that's probably not a good general solution).

**Comment by Xaviju** [comment]
Thanks for reporting, i'll review it.

**Comment by Moini** [comment]
Thank you, @Xaviju !

**Comment by Moini** [comment]
Thx!

**Comment by Xaviju** [comment]
Thank you! I totally forgot this!
