### ISSUE TITLE
Image licence / author should be mentioned

### ISSUE THREAD

**Issue by Moini** [Xaviju/inkscape-placeholder#2]
It is impossible from inside Inkscape to see the licence and author of the images that are pulled in from the web.

So wouldn't it make sense to add this info to the readme file:

Lorempixel images: CC-By-SA (but useless without author info)
Unsplash Images: CC-0
Uifaces: for private mockups only (no publishing)  

and to warn users to never use the extension (except the Unsplash one) for any other purpose than for mockups?
(Could also be added into the .inx files)

**Comment by Xaviju** [comment]
You are completely right. I like the idea of publishing a warning. Something similar to LoremPixel including the license of the three services:

> The provided images are for layout purposes and each image we use for this project is released under the creative commons license (CC BY-SA). For more information visit http://creativecommons.org/licenses/
> So, if you want to use the images for more than just layouts, you have to double check the license and ask the author. For this we will link to each photographer's flickr page. Furthermore, we assume no liability.

What do you think?

**Comment by Moini** [comment]
While I don't think it's feasible to include the flickr page link (or it could be possible to put it into some unused attribute... 'inkscape:label'? using 'title' could break things for some... 'alt' maybe?),  yes, I was thinking of something along those lines. I think the following is a bit too long, maybe...:

> The images imported by this extension set are intended for use in private mockups only. If you would like to use them for any other purpose, please make sure to double check the image's license.
> - Images from [Lorempixel](http://lorempixel.com/) are released under the [Creative Commons Attribution Share Alike License ](https://creativecommons.org/licenses/by-sa/4.0/)(CC-By-SA), which requires you to name the author and to share your work under the same license. 
> - Images from [Unsplash](https://unsplash.com/) are released under the [CC-0 License](https://creativecommons.org/publicdomain/zero/1.0/legalcode), and can be used for any purpose.
> - Images from [Uifaces](http://uifaces.com/) may only be used for private mockups (no publishing).
> 
> As these websites' licensing terms may change any time, we do not assume any liability for the above information. You should always check the license of images you use in your art and other published works carefully.

**Comment by Xaviju** [comment]
That text looks great and well structured. I like it.

The only thing is when I request a random image in Lorempixel ( [Like this](http://lorempixel.com/400/200/) ) they do not provide any information about the author. The only way to link author and image is through Lorempixel's website. 
We could add this information to the readme so the users know where to find the author to attribute the work.

> The images imported by this extension set are intended for use in private mockups only. If you would like to use them for any other purpose, please make sure to double check the image's license: 
> - Images from Lorempixel are released under the Creative Commons Attribution Share Alike License (CC-By-SA), which requires you to name the author and to share your work under the same license. Find the image author on [Lorempixel's website](http://lorempixel.com/).
> - Images from Unsplash are released under the CC-0 License, and can be used for any purpose.
> - Images from Uifaces may only be used for private mockups (no publishing).
> 
> As these websites licensing terms may change any time, we do not assume any liability for the above information. You should always check the license of images you use in your art and other published works carefully.

**Comment by Moini** [comment]
I'd put the apostrophe back in after 'websites' (at the bottom, plural+genitive), but for the rest: 
Sounds good :) Thank you!
